// Auto-generated by scripts/generate-firebase-config.js
// Do not edit this file manually; values are injected from Netlify/CI env vars.
window.FIREBASE_CONFIG = {};
window.FIREBASE_AUTH_PROVIDERS = [
  "google"
];
