// Auto-generated by scripts/generate-firebase-config.js
// Do not edit this file manually; values are injected from Netlify/CI env vars.
window.FIREBASE_CONFIG = {};
window.FIREBASE_AUTH_PROVIDERS = [
  "google"
];
window.FIREBASE_RECAPTCHA_V3_SITE_KEY = "6LfFeS8sAAAAAH9hsS136zJ6YOQkpRZKniSIIYYI";
window.FIREBASE_APP_CHECK_SITE_KEY = "6LfFeS8sAAAAAH9hsS136zJ6YOQkpRZKniSIIYYI"; // Backwards compatibility
window.FIREBASE_APP_CHECK_ENABLED = "true";
window.SHARED_ADMIN_EMAILS = [
  "mr.lion1995@gmail.com"
];
