// Auto-generated by scripts/generate-version.js
// Do not edit this file manually.
self.CSSMATE_BUILD_META = { appVersion: "2025.13.0", buildTime: "2025-12-24T10:23:04.361Z", gitSha: "1c6ada780ccc", buildId: "2025.13.0+1c6ada780ccc", cacheKey: "2025.13.0-1c6ada780ccc-2025-12-24T10-23-04.361Z", allowedFirebaseProjects: ["sscaff-43a33"] };
self.CSSMATE_APP_VERSION = "2025.13.0-1c6ada780ccc-2025-12-24T10-23-04.361Z";
