// Auto-generated by scripts/generate-version.js
// Do not edit this file manually.
self.CSSMATE_BUILD_META = { appVersion: "2025.13.0", buildTime: "2025-12-29T17:44:50.784Z", gitSha: "dev", buildId: "2025.13.0+dev", cacheKey: "2025.13.0-dev-2025-12-29T17-44-50.784Z", allowedFirebaseProjects: [] };
self.CSSMATE_APP_VERSION = "2025.13.0-dev-2025-12-29T17-44-50.784Z";
