// Auto-generated by scripts/generate-version.js
// Do not edit this file manually.
self.CSSMATE_BUILD_META = { appVersion: "2025.13.0", buildTime: "2026-01-13T17:44:52.645Z", gitSha: "dev", buildId: "2025.13.0+dev", cacheKey: "2025.13.0-dev-2026-01-13T17-44-52.645Z", buildContext: "", deployUrl: "", siteUrl: "" };
self.CSSMATE_APP_VERSION = "2025.13.0-dev-2026-01-13T17-44-52.645Z";
