// Auto-generated by scripts/generate-auth0-config.mjs
(function () {
  const config = {
  "VITE_AUTH0_DOMAIN": "",
  "VITE_AUTH0_CLIENT_ID": "",
  "VITE_AUTH0_AUDIENCE": "",
  "VITE_ADMIN_EMAIL": "",
  "VITE_ADMIN_EMAILS": "",
  "VITE_AUTH0_REDIRECT_URI": "",
  "VITE_E2E_BYPASS_AUTH": ""
}
  if (typeof window !== 'undefined') {
    window.__ENV__ = Object.assign({}, window.__ENV__ || {}, config)
    Object.assign(window, config)
  }
})()
