// Auto-generated by scripts/generate-auth0-config.mjs
(function () {
  const config = {
    VITE_AUTH0_DOMAIN: "",
    VITE_AUTH0_CLIENT_ID: "",
    VITE_AUTH0_AUDIENCE: "",
    VITE_ADMIN_EMAIL: ""
  }
  if (typeof window !== 'undefined') {
    Object.assign(window, config)
    window.__ENV__ = Object.assign({}, window.__ENV__ || {}, config)
  }
})()
