import { mkdirSync, writeFileSync, readFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const repoRoot = path.join(__dirname, '..')

function loadPackageVersion () {
  const pkgPath = path.join(repoRoot, 'package.json')
  const pkgRaw = readFileSync(pkgPath, 'utf8')
  const pkg = JSON.parse(pkgRaw)
  return pkg.version || '0.0.0'
}

function resolveBuildTime () {
  return process.env.VITE_BUILD_TIME || new Date().toISOString()
}

function resolveGitSha () {
  const rawSha = process.env.VITE_GIT_SHA || process.env.GIT_COMMIT_SHA || process.env.COMMIT_REF || ''
  if (!rawSha) return 'dev'
  return rawSha.slice(0, 12)
}

function resolveBuildContext () {
  const context = process.env.CONTEXT || process.env.NETLIFY_CONTEXT || ''
  return context || ''
}

function resolveDeployUrl () {
  return process.env.URL || ''
}

function resolveSiteUrl () {
  return process.env.URL || ''
}

function buildCacheKey ({ version, gitSha, buildTime }) {
  const stamp = `${version}+${gitSha}+${buildTime}`
  return stamp.replace(/[^a-zA-Z0-9._-]/g, '-')
}

function writeFile (targetPath, contents) {
  const dir = path.dirname(targetPath)
  mkdirSync(dir, { recursive: true })
  writeFileSync(targetPath, contents, 'utf8')
  console.log(`[version] Wrote ${path.relative(repoRoot, targetPath)}`)
}

function buildModuleSource ({ version, buildTime, gitSha, buildId, cacheKey, buildContext, deployUrl, siteUrl }) {
  const banner = '// Auto-generated by scripts/generate-version.js\n// Do not edit this file manually.\n'
  return `${banner}export const APP_VERSION = ${JSON.stringify(version)};\nexport const BUILD_TIME = ${JSON.stringify(buildTime)};\nexport const GIT_SHA = ${JSON.stringify(gitSha)};\nexport const BUILD_ID = ${JSON.stringify(buildId)};\nexport const CACHE_KEY = ${JSON.stringify(cacheKey)};\nexport const BUILD_CONTEXT = ${JSON.stringify(buildContext)};\nexport const DEPLOY_URL = ${JSON.stringify(deployUrl)};\nexport const SITE_URL = ${JSON.stringify(siteUrl)};\n\nexport function getBuildMetadata () {\n  return {\n    appVersion: APP_VERSION,\n    buildTime: BUILD_TIME,\n    gitSha: GIT_SHA,\n    buildId: BUILD_ID,\n    cacheKey: CACHE_KEY,\n    buildContext: BUILD_CONTEXT,\n    deployUrl: DEPLOY_URL,\n    siteUrl: SITE_URL,\n  };\n}\n`;
}

function buildGlobalSource ({ version, buildTime, gitSha, buildId, cacheKey, buildContext, deployUrl, siteUrl }) {
  const banner = '// Auto-generated by scripts/generate-version.js\n// Do not edit this file manually.\n'
  return `${banner}self.CSSMATE_BUILD_META = { appVersion: ${JSON.stringify(version)}, buildTime: ${JSON.stringify(buildTime)}, gitSha: ${JSON.stringify(gitSha)}, buildId: ${JSON.stringify(buildId)}, cacheKey: ${JSON.stringify(cacheKey)}, buildContext: ${JSON.stringify(buildContext)}, deployUrl: ${JSON.stringify(deployUrl)}, siteUrl: ${JSON.stringify(siteUrl)} };\nself.CSSMATE_APP_VERSION = ${JSON.stringify(cacheKey)};\n`;
}

function main () {
  const appVersion = loadPackageVersion()
  const buildTime = resolveBuildTime()
  const gitSha = resolveGitSha()
  const buildContext = resolveBuildContext()
  const deployUrl = resolveDeployUrl()
  const siteUrl = resolveSiteUrl()
  const buildId = `${appVersion}+${gitSha}`
  const cacheKey = buildCacheKey({ version: appVersion, gitSha, buildTime })

  const moduleSource = buildModuleSource({
    version: appVersion,
    buildTime,
    gitSha,
    buildId,
    cacheKey,
    buildContext,
    deployUrl,
    siteUrl,
  })
  const globalSource = buildGlobalSource({
    version: appVersion,
    buildTime,
    gitSha,
    buildId,
    cacheKey,
    buildContext,
    deployUrl,
    siteUrl,
  })

  writeFile(path.join(repoRoot, 'src', 'version.js'), moduleSource)
  writeFile(path.join(repoRoot, 'js', 'version.js'), globalSource)
}

main()
