// Auto-generated by scripts/generate-version.js
// Do not edit this file manually.
export const APP_VERSION = "2025.13.0";
export const BUILD_TIME = "2025-12-21T21:26:44.089Z";
export const GIT_SHA = "dev";
export const BUILD_ID = "2025.13.0+dev";
export const CACHE_KEY = "2025.13.0-dev-2025-12-21T21-26-44.089Z";
export const ALLOWED_FIREBASE_PROJECTS = [];

export function getBuildMetadata () {
  return {
    appVersion: APP_VERSION,
    buildTime: BUILD_TIME,
    gitSha: GIT_SHA,
    buildId: BUILD_ID,
    cacheKey: CACHE_KEY,
    allowedFirebaseProjects: ALLOWED_FIREBASE_PROJECTS,
  };
}
