// Auto-generated by scripts/generate-version.js
// Do not edit this file manually.
export const APP_VERSION = "2025.13.0";
export const BUILD_TIME = "2025-12-24T10:35:05.838Z";
export const GIT_SHA = "1c6ada780ccc";
export const BUILD_ID = "2025.13.0+1c6ada780ccc";
export const CACHE_KEY = "2025.13.0-1c6ada780ccc-2025-12-24T10-35-05.838Z";
export const ALLOWED_FIREBASE_PROJECTS = ["sscaff-43a33"];

export function getBuildMetadata () {
  return {
    appVersion: APP_VERSION,
    buildTime: BUILD_TIME,
    gitSha: GIT_SHA,
    buildId: BUILD_ID,
    cacheKey: CACHE_KEY,
    allowedFirebaseProjects: ALLOWED_FIREBASE_PROJECTS,
  };
}
