// Auto-generated by scripts/generate-version.js
// Do not edit this file manually.
export const APP_VERSION = "2025.13.0";
export const BUILD_TIME = "2026-01-13T19:23:21.422Z";
export const GIT_SHA = "dev";
export const BUILD_ID = "2025.13.0+dev";
export const CACHE_KEY = "2025.13.0-dev-2026-01-13T19-23-21.422Z";
export const BUILD_CONTEXT = "";
export const DEPLOY_URL = "";
export const SITE_URL = "";

export function getBuildMetadata () {
  return {
    appVersion: APP_VERSION,
    buildTime: BUILD_TIME,
    gitSha: GIT_SHA,
    buildId: BUILD_ID,
    cacheKey: CACHE_KEY,
    buildContext: BUILD_CONTEXT,
    deployUrl: DEPLOY_URL,
    siteUrl: SITE_URL,
  };
}
